# Generated by Django 2.1.3 on 2018-11-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(max_length=200)),
                ('categories', models.CharField(max_length=800)),
                ('countries', models.CharField(max_length=200)),
                ('network', models.CharField(max_length=200)),
                ('tussenstukje', models.CharField(max_length=200)),
            ],
        ),
    ]
