# Generated by Django 2.1.3 on 2018-12-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninja_partner_stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='store',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='store',
            name='countries',
        ),
        migrations.AddField(
            model_name='store',
            name='category',
            field=models.ManyToManyField(to='ninja_partner_stores.Category'),
        ),
        migrations.AddField(
            model_name='store',
            name='country',
            field=models.ManyToManyField(to='ninja_partner_stores.Country'),
        ),
    ]
