# Generated by Django 2.1.3 on 2018-12-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninja_partner_stores', '0002_auto_20181204_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='tussenstukjeversietwee',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
