# Generated by Django 2.1.3 on 2018-12-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninja_partner_stores', '0003_store_tussenstukjeversietwee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='tussenstukjeversietwee',
        ),
        migrations.AddField(
            model_name='store',
            name='tussenstukjetwee',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
