# Generated by Django 2.1.2 on 2018-11-09 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rewards'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rewards',
        ),
    ]
