# Generated by Django 2.1.3 on 2018-12-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20181212_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ninja_user',
            field=models.BooleanField(default=False),
        ),
    ]
