# Generated by Django 2.1.3 on 2019-01-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_ninja_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_picked_project',
            field=models.CharField(default='biogasInstallation', max_length=200),
        ),
    ]
