# Generated by Django 2.1.3 on 2019-01-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_user_picked_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_picked_project',
            field=models.CharField(max_length=200),
        ),
    ]
