# Generated by Django 2.1.3 on 2019-01-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190103_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_picked_project',
            field=models.IntegerField(),
        ),
    ]
