# Generated by Django 2.1.3 on 2018-11-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_stores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='Website',
            new_name='website',
        ),
        migrations.RemoveField(
            model_name='store',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='store',
            name='categories',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='store',
            name='countries',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='store',
            name='network',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='tussenstukje',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
